"""empty message

Revision ID: 1685e3d3db13
Revises: b2b95dce1289
Create Date: 2020-11-07 10:30:32.544151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1685e3d3db13'
down_revision = 'b2b95dce1289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('actor', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('releasedate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'releasedate')
    op.drop_column('actor', 'gender')
    op.drop_column('actor', 'age')
    # ### end Alembic commands ###
