"""empty message

Revision ID: 8db8392dd8d3
Revises: 1685e3d3db13
Create Date: 2020-11-07 10:58:42.025076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db8392dd8d3'
down_revision = '1685e3d3db13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('actor', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movie', 'releasedate',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'releasedate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('actor', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
